library(tidyverse)
library(plyr)
library(lme4)
library(lmerTest)
to_analyze <- read_csv('to_analyze.csv')
for_corr = na.omit(select(to_analyze, -HDRS, -Y2RS))
cor.test(for_corr$mean_pause, for_corr$unique_num, method ="spearman")
cor.test(for_corr$PANSS_Total, for_corr$unique_num, method ="spearman")
kruskal.test(for_corr$unique_num~for_corr$binary_diagnosis)


to_analyze = na.omit(select(to_analyze, -HDRS, -Y2RS, -mean_pause))
to_analyze <- column_to_rownames(to_analyze, var = "ID")
# to_analyze$binary_diagnosis <- as.factor(to_analyze$binary_diagnosis)
# to_analyze$ID <- as.factor(to_analyze$ID)
lm1 <- lmer(binary_diagnosis~ (1|unique_num) + (1|repeat_num) + no_pos_min_cos_sim + no_pos_mean_cos_sim + no_pos_max_cos_sim, to_analyze)
summary(lm1)
lm2 <- lmer(PANSS_Total ~ (1|unique_num) + (1|repeat_num) + no_pos_min_cos_sim + no_pos_mean_cos_sim + no_pos_max_cos_sim, to_analyze)
summary(lm2)
lm3 <- lmer(PANSS_P ~ (1|unique_num) + (1|repeat_num) + no_pos_min_cos_sim + no_pos_mean_cos_sim + no_pos_max_cos_sim, to_analyze)
summary(lm3)
lm4 <- lmer(PANSS_N ~ (1|unique_num) + (1|repeat_num) + no_pos_min_cos_sim + no_pos_mean_cos_sim + no_pos_max_cos_sim, to_analyze)
summary(lm4)
lm5 <- lmer(PANSS_O ~ (1|unique_num) + (1|repeat_num) + no_pos_min_cos_sim + no_pos_mean_cos_sim + no_pos_max_cos_sim, to_analyze)
summary(lm5)

lm1_man <- lmer(binary_diagnosis~ (1|unique_num) + (1|repeat_num) + min_cluster_len + mean_cluster_len + max_cluster_len, to_analyze)
summary(lm1_man)
lm2_man <- lmer(PANSS_Total ~ (1|unique_num) + (1|repeat_num) + min_cluster_len + mean_cluster_len + max_cluster_len, to_analyze)
summary(lm2_man)
lm3_man <- lmer(PANSS_P ~ (1|unique_num) + (1|repeat_num) + min_cluster_len + mean_cluster_len + max_cluster_len, to_analyze)
summary(lm3_man)
lm4_man <- lmer(PANSS_N ~ (1|unique_num) + (1|repeat_num) + min_cluster_len + mean_cluster_len + max_cluster_len, to_analyze)
summary(lm4_man)
lm5_man <- lmer(PANSS_O ~ (1|unique_num) + (1|repeat_num) + min_cluster_len + mean_cluster_len + max_cluster_len, to_analyze)
summary(lm5_man)
